import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Ekomart-Grocery-Store(e-Commerce) HTML Template",
    description: "Generated by create next app",
    icons: {
        icon: [
            {
                url: "/assets/images/fav.png",
                type: "image/x-icon",
            },
        ],
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="dashboard-wrapper">
            {children}
        </div>
    );
}
